//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KristiLakeTrailPOI_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointOfInterest
    {
        public int ID { get; set; }
        public string PointTitle { get; set; }
        public string PointInterest { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime EditedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public string meta01 { get; set; }
        public string meta02 { get; set; }
        public int PointID { get; set; }
    }
}
